const MEGA_CAP = new Set(['AAPL','ABBV','ADBE','AMAT','AMD','AMZN','AVGO','BAC','BLK','BRK-B','CAT','COST','CRM','CVX','DIS','GE','GEV','GOOGL','GS','HD','IBM','JNJ','JPM','KO','LIN','LLY','MA','MCD','META','MRK','MS','MSFT','MU','NFLX','NVDA','ORCL','PEP','PG','PLTR','QCOM','TMO','TMUS','TSLA','UNH','V','VZ','WFC','WMT','XOM']);
const MEGA_CAP_500B = new Set(['AAPL','AMZN','AVGO','BRK-B','GOOGL','JNJ','JPM','LLY','MA','META','MSFT','NVDA','TSLA','UNH','V','WMT','XOM']);

const TOP_VOL = new Set(['SPY','QQQ','IWM','EEM','XLF','HYG','SMH','GDX','SLV','IBIT']);
const SPDR = new Set(['SPY','GLD','SPLG','XLK','XLF','DIA','SPYG','BIL','XLV','XLE','SPDW','GLDM','SPYV','XLI','XLC','MDY','XLU','XLY','SDY','XLP','SPEM','SPMD','SPSM','SPTM','SPSM','SPTL','SPIB','SPHY','SPTI','SPAB','SPSB','XBI','XLRE','JNK','SPYD','XLB','SPMB','XAR','SPTS','CWB','SRLN','FEZ','SJNK','GNR','XME','SLYV','SLYG','TOTL','BILS','KRE','SHM','TFI','HYMB','FLRN','MDYG','CWI','MDYV','XOP','KOMP','SPYX','EBND','SPBO','TIPX','RWR','XHB','XSD','BWX','QUS','XNTK','SPGM']);
const VANGUARD = new Set(['VOO','VTI','VEA','VUG','VTV','BND','VXUS','VWO','VGT','VIG','VO','BNDX','VYM','VB','VCIT','VT','VEU','VV','BSV','VTEB','VCSH','VGIT','VONG','VNQ','VBR','VGK','MGK','BIV','VGSH','VXF','VOE','VOOG','VBK','VYMI','VOT','VHT','VONV','VTIP','VMBS','VTWO','VFH','MGV','VSS','ESGV','VGLT','MGC','VDE','VIGI','VPL','VPU','VDC','VUSB']);

const TOP_AUM = new Set(['SPY','IVV','VOO','VTI','QQQ','VEA','VTV','IEFA','BND','AGG','VWO','IWM','IEMG','VIG','VUG','IJR','VXUS','GLD','IJH','SCHD','VGT','XLK','BNDX','VO','IWF','VCIT','XLV','ITOT','BSV','DIA']);
const VANECK_ETFS = new Set(['AFK','ANGL','BBH','BIZD','CLOB','CLOI','CRAK','DAPP','EINC','EMBX','EMLC','ESPO','ETHV','FLTR','GDX','GDXJ','GLIN','GPZ','GRNB','HAP','HODL','HYD','HYEM','ISRA','ITM','MLN','MOAT','MOO','MORT','MOTI','NLR','OIH','OUNZ','PFXF','PIT','PPH','RAAX','REMX','RTH','SHYD','SLX','SMB','SMH','SMHX','SMOG','SMOT','VNM','XMPT']);
const COMMODITY_ETFS = new Set(['COPX','DBA','DBC','ETHA','GDX','GLD','IBIT','PPLT','SIL','SLV','UNG','USO','XME']);
const SECTOR_ETFS = new Set([
  'ARKF','ARKG','ARKK','ARKQ','ARKW','BITQ','BLOK','CIBR','CNCR','CQQQ','DFEN','EEM','FAN','FDIS','FDN','FHLC','FTEC','GRID','HACK','IBB','IBIT','ICLN','IFRA','IGV','IHF','IHI','ITA','ITB','IYE','IYF','IYH','IYR','IYT','IYW','IYZ','IZRL','JETS','KBE','KIE','KRE','KWEB','MJ','MSOS','ONLN','PAVE','PBE','PBW','PHO','PJP','PPH','PRNT','PSCT','PSI','QCLN','QQQJ','QTEC','ROBO','SKYY','SLV','SOXQ','SOXX','TAN','URNM','WOOD','XAR','XBI','XHB','XHE','XLB','XLC','XLE','XLF','XLI','XLK','XLP','XLRE','XLU','XLV','XLY','XME','XNTK','XOP','XRT','XSD','XSW','YOLO',
  'AIQ','ARGT','AUSF','BKCH','BOTZ','BUG','CATH','CHIQ','CLIP','CLOU','COPX','DAX','DIV','DJIA','DRIV','DTCR','EMBD','FINX','GOEX','GREK','GXIG','KRMA','LIT','MLPA','MLPX','NORW','ONOF','PFFD','PFFV','QYLG','QYLD','RSSL','RYLD','SDIV','SHLD','SIL','SNSR','SPFF','SRET','URA','XYLD','ZAP',
  'CHAT','MAGS','METV','QDTE','RDTE','XDTE','XPAY','YBTC',
  'AGGY','AIVL','BTCW','CXSE','DDLS','DDWM','DEM','DES','DEW','DFE','DFJ','DGRE','DGRS','DGRW','DGS','DHS','DIM','DLN','DLS','DNL','DOL','DON','DTD','DTH','DWM','DXJ','EES','ELD','EMMF','EPI','EPS','EZM','GDE','GDMN','HEDJ','HYZD','IHDG','IQDG','NTSI','NTSX','QGRW','QHY','UNIY','USFR','USDU','USMF','WCLD','WTAI','WTMF','WTV','XSOE'
]);

const ALL_ETFS = new Set([...TOP_AUM, ...TOP_VOL, ...SPDR, ...VANGUARD, ...VANECK_ETFS, ...COMMODITY_ETFS, ...SECTOR_ETFS]);
const SPDR_SECTORS = new Set(['SPY','XLE','XLK','XLB','XLV','XLY','XLI','XLC','XLU','XLF','XLRE','XLP']);
const INDEX_SYMBOLS = new Set(['SPY','QQQ','DIA','IWM']);
const MAJOR_TARGETS = new Set([...INDEX_SYMBOLS, ...TOP_AUM, ...MEGA_CAP_500B]);
